runtime: php55
api_version: 1
instance_class: F1

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: 10s
  max_pending_latency: 15s

handlers:
- url: /activity.*
  script: activity.php
- url: /.*
  script: proxy.php